### ISSUE TITLE
UnicodeDecodeError and AttributeError

### ISSUE THREAD

**Issue by kongwenbin** [blark/aiodnsbrute#2]
Hello, thanks for creating this tool. I wanted to try it out but there seem to be 2 issues that I am facing:
1. `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 167457: invalid continuation byte` 
2. `AttributeError: 'aioDNSBrute' object has no attribute 'pbar'`

I followed the steps to create `virtualenv` as per instructions and also installed the application using `pipsi install .`. 

Below is the full error message: 
```
root@kali:/opt# aiodnsbrute -w test.txt -vv -t 1024 google.com
[*] Brute forcing google.com with a maximum of 1024 concurrent tasks...
Traceback (most recent call last):
  File "/root/.local/venvs/aiodnsbrute/lib/python3.5/site-packages/aiodnsbrute/cli.py", line 86, in run
    w = words.read().splitlines()
  File "/root/.local/venvs/aiodnsbrute/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 167457: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/bin/aiodnsbrute", line 11, in <module>
    sys.exit(main())
  File "/root/.local/venvs/aiodnsbrute/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/root/.local/venvs/aiodnsbrute/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/root/.local/venvs/aiodnsbrute/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.local/venvs/aiodnsbrute/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/root/.local/venvs/aiodnsbrute/lib/python3.5/site-packages/aiodnsbrute/cli.py", line 122, in main
    results = bf.run(wordlist=wordlist, domain=domain, recursive=recursive)
  File "/root/.local/venvs/aiodnsbrute/lib/python3.5/site-packages/aiodnsbrute/cli.py", line 104, in run
    self.pbar.close()
AttributeError: 'aioDNSBrute' object has no attribute 'pbar'
```

**Comment by blark** [comment]
Thanks for the report, I will look at it tonight.

**Comment by ghost** [comment]
1. Use: open('file.txt', encoding='utf-8', errors='ignore')
And all errors - will disappear) See my fork

**Comment by blark** [comment]
Implemented change in dev branch. Thanks!
